replicaCount: 1

image:
  repository: localhost:5000/card-shoggoths
  pullPolicy: IfNotPresent
  tag: "1.2.0"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/websocket-services: card-shoggoths
  hosts:
    - host: poker.fazigu.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: true
    secretName: poker-tls
    hosts:
      - poker.fazigu.org

certManager:
  enabled: true
  issuer:
    name: letsencrypt-prod
    kind: ClusterIssuer

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5
